name: 'Cypress e2e parallel test action'
inputs:
  group:
    description: 'The current test group.'
    default: 1
  groups:
    description: 'The total number of test groups.'
    default: 1
  spec:
    description: 'A glob that matches the test files.'
    default: 'cypress/integration/*spec.js'

outputs:
  tests:
    description: 'The tests to be run for this group'

runs:
  using: 'node16'
  main: 'dist/index.js'
